# Generated by Django 3.2.25 on 2025-07-28 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('local_evento', models.CharField(max_length=200)),
                ('data_evento', models.DateField(help_text='Data para realização do evento')),
                ('link', models.URLField(help_text='Link para site de inscrição do Evento')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-data_evento'],
            },
        ),
    ]
