# Generated by Django 3.2.25 on 2025-07-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='noticias/')),
                ('titulo', models.CharField(max_length=100)),
                ('texto', models.TextField()),
                ('data_noticia', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
