# Generated by Django 3.2.25 on 2025-08-10 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_ambiente', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('sobre_ambiente', models.TextField()),
                ('site_ambiente', models.URLField(help_text='Link do site referente ao ambiente')),
            ],
        ),
    ]
