# Generated by Django 3.2.25 on 2025-08-08 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_startup', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('nome_startup', models.CharField(max_length=100)),
                ('descricao_startup', models.TextField()),
                ('site', models.URLField(help_text='Link para o site da startup')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
