# Generated by Django 3.2.25 on 2025-07-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('link', models.URLField(help_text='Link da página do curso ofertado')),
                ('data_criacao', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
