# Generated by Django 3.2.25 on 2025-07-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encontros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(max_length=200)),
                ('descricao', models.TextField()),
                ('local_encontro', models.CharField(max_length=255)),
                ('data_encontro', models.DateField(help_text='Data para realização do encontro')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('link', models.URLField(help_text='Link para inscrição do encontro')),
            ],
            options={
                'ordering': ['-data_encontro'],
            },
        ),
    ]
