# Generated by Django 3.2.25 on 2025-07-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_empresa', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('nome_empresa', models.CharField(max_length=100)),
                ('site', models.URLField()),
                ('descricao', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
